from selene import browser, be, have, command
import os
def test_fill_form(browser_personal_settings):
    browser.open('/automation-practice-form')
    browser.element('[id="firstName"]').should(be.blank).type('Ivan')
    browser.element('[id="lastName"]').should(be.blank).type('Neverov')
    browser.element('[id="userEmail"]').should(be.blank).type('neverovsky@mail.ru')
    browser.element('[for="gender-radio-1"]').click()
    browser.element('[id="userNumber"]').should(be.blank).type('8927654341')
    browser.element('[id="dateOfBirthInput"]').click()
    browser.element('[class="react-datepicker__year-select"]').click()
    browser.element('[value="1999"]').click()
    browser.element('[class="react-datepicker__month-select"]').click()
    browser.element('[value="8"]').click()
    browser.element('[class="react-datepicker__day react-datepicker__day--008"]').click()
    browser.element('[id="subjectsInput"]').should(be.blank).type('Physics').press_enter()
    browser.element('[id="subjectsInput"]').perform(command.js.scroll_into_view)
    browser.element('[for="hobbies-checkbox-1"]').click()
    browser.element('[id="uploadPicture"]').send_keys(os.path.abspath('1.jpg'))
    browser.element('[id="currentAddress"]').should(be.blank).type('Saint-Petersburg')
    browser.element('[id="react-select-3-input"]').should(be.blank).type('NCR').press_enter()
    browser.element('[id="react-select-4-input"]').should(be.blank).type('Delhi').press_enter()
    browser.element('[id="submit"]').click()

    browser.element('[class="modal-content"]').should(have.text('Ivan Neverov'))
    browser.element('[class="modal-content"]').should(have.text('neverovsky@mail.ru'))
    browser.element('[class="modal-content"]').should(have.text('Male'))
    browser.element('[class="modal-content"]').should(have.text('8927654341'))
    browser.element('[class="modal-content"]').should(have.text('08 September,1999'))
    browser.element('[class="modal-content"]').should(have.text('Physics'))
    browser.element('[class="modal-content"]').should(have.text('Sports'))
    browser.element('[class="modal-content"]').should(have.text('1.jpg'))
    browser.element('[class="modal-content"]').should(have.text('Saint-Petersburg'))
    browser.element('[class="modal-content"]').should(have.text('NCR Delhi'))